import { execFile } from "node:child_process";
import { access, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { createRequire } from "node:module";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { promisify } from "node:util";

import { fal } from "@fal-ai/client";

import { traceTool } from "@/lib/langfuse";

const execFileAsync = promisify(execFile);
const require = createRequire(import.meta.url);

const partyMusicAssetPath = join(
  process.cwd(),
  "public",
  "audio",
  "party-music.mp3"
);
const defaultVideoDurationSeconds = 15;
const maxMuxedVideoDurationSeconds = 20;
const finalVideoBitrateKbps = 4500;
const finalVideoAudioBitrateKbps = 96;

export async function muxVoiceOverIntoVideo(
  videoUrl: string,
  voiceOverUrl: string,
  targetDurationSeconds = maxMuxedVideoDurationSeconds,
  musicBedUrl?: string
) {
  return traceTool(
    "mux-voice-over",
    () =>
      muxVoiceOverIntoVideoInner(
        videoUrl,
        voiceOverUrl,
        targetDurationSeconds,
        musicBedUrl
      ),
    {
      metadata: {
        targetDurationSeconds,
        hasMusicBed: Boolean(musicBedUrl)
      }
    }
  );
}

async function muxVoiceOverIntoVideoInner(
  videoUrl: string,
  voiceOverUrl: string,
  targetDurationSeconds: number,
  musicBedUrl?: string
) {
  const ffmpegBin = getFfmpegPath();

  if (!ffmpegBin) {
    throw new Error("ffmpeg binary is not available.");
  }

  const workspace = await mkdtemp(join(tmpdir(), "birthdaybot-voice-"));

  try {
    const [video, voiceOver, musicBed] = await Promise.all([
      mediaUrlToBuffer(videoUrl),
      mediaUrlToBuffer(voiceOverUrl),
      musicBedUrl
        ? mediaUrlToBuffer(musicBedUrl).catch(() => undefined)
        : Promise.resolve(undefined)
    ]);

    const inputVideo = join(workspace, "input.mp4");
    const inputVoice = join(workspace, "voice-over.mp3");
    const outputVideo = join(workspace, "voiced-output.mp4");

    await writeFile(inputVideo, video.bytes);
    await writeFile(inputVoice, voiceOver.bytes);

    let aiMusicPath: string | undefined;

    if (musicBed && musicBed.bytes.byteLength > 0) {
      aiMusicPath = join(workspace, "ai-music.mp3");
      await writeFile(aiMusicPath, musicBed.bytes);
    }

    const muxDurationSeconds = await finalMuxedVideoDurationSeconds(
      ffmpegBin,
      inputVoice,
      targetDurationSeconds
    );
    const partyMusicInput = await partyMusicInputArgs(aiMusicPath);

    await execFileAsync(
      ffmpegBin,
      muxFfmpegArgs({
        inputVideo,
        inputVoice,
        outputVideo,
        partyMusicInput,
        durationSeconds: muxDurationSeconds,
        videoBitrateKbps: finalVideoBitrateKbps
      })
    );

    const outputBytes = await readFile(outputVideo);

    return fal.storage.upload(
      new File([outputBytes], "birthday-video-with-voice.mp4", {
        type: "video/mp4"
      })
    );
  } finally {
    await rm(workspace, { force: true, recursive: true });
  }
}

function muxFfmpegArgs({
  inputVideo,
  inputVoice,
  outputVideo,
  partyMusicInput,
  durationSeconds,
  videoBitrateKbps
}: {
  inputVideo: string;
  inputVoice: string;
  outputVideo: string;
  partyMusicInput: string[];
  durationSeconds: number;
  videoBitrateKbps: number;
}) {
  return [
    "-y",
    "-i",
    inputVideo,
    "-i",
    inputVoice,
    ...partyMusicInput,
    "-t",
    String(durationSeconds),
    "-filter_complex",
    [
      // Voice bus: gain-up, gentle compression, split for sidechain key + final mix
      "[1:a:0]volume=1.45,acompressor=threshold=-18dB:ratio=3:attack=5:release=80,asplit=2[voice_main][voice_key]",
      // Music bus: nominal gain, padded so we always have audio for the full duration
      "[2:a:0]volume=0.32,apad[music_pre]",
      // Sidechain duck: music is ATTENUATED in real time when the voice key is present
      "[music_pre][voice_key]sidechaincompress=threshold=0.05:ratio=8:attack=8:release=320:makeup=1[music_ducked]",
      // Final mix: voice + ducked music, then loudness-normalize to social/mobile target (-16 LUFS)
      "[voice_main][music_ducked]amix=inputs=2:duration=first:dropout_transition=0:normalize=0,loudnorm=I=-16:LRA=11:TP=-1.5,alimiter=limit=0.97[aout]"
    ].join(";"),
    "-map",
    "0:v:0",
    "-map",
    "[aout]",
    "-vf",
    "scale='if(gte(iw,ih),-2,720)':'if(gte(iw,ih),720,-2)'",
    "-c:v",
    "libx264",
    "-preset",
    "veryfast",
    "-b:v",
    `${videoBitrateKbps}k`,
    "-maxrate",
    `${videoBitrateKbps}k`,
    "-bufsize",
    `${videoBitrateKbps * 2}k`,
    "-pix_fmt",
    "yuv420p",
    "-c:a",
    "aac",
    "-b:a",
    `${finalVideoAudioBitrateKbps}k`,
    "-shortest",
    "-metadata",
    "comment=AI-generated by BirthdayBot - voice cloned via ElevenLabs",
    "-movflags",
    "+faststart",
    outputVideo
  ];
}

async function partyMusicInputArgs(aiMusicPath?: string) {
  if (aiMusicPath) {
    return ["-stream_loop", "-1", "-i", aiMusicPath];
  }

  try {
    await access(partyMusicAssetPath);
    return ["-stream_loop", "-1", "-i", partyMusicAssetPath];
  } catch {
    return ["-f", "lavfi", "-i", partyMusicLavfiSource()];
  }
}

async function finalMuxedVideoDurationSeconds(
  ffmpegBin: string,
  inputVoice: string,
  targetDurationSeconds: number
) {
  const target = Math.max(1, targetDurationSeconds || defaultVideoDurationSeconds);
  const voiceDuration = await audioDurationSeconds(ffmpegBin, inputVoice);
  const neededForVoice = Math.ceil((voiceDuration || 0) + 0.75);

  return Math.min(Math.max(target, neededForVoice), maxMuxedVideoDurationSeconds);
}

async function audioDurationSeconds(ffmpegBin: string, inputAudio: string) {
  try {
    const { stderr } = await execFileAsync(ffmpegBin, [
      "-hide_banner",
      "-i",
      inputAudio
    ]);

    return durationSecondsFromFfmpegOutput(stderr);
  } catch (error) {
    const stderr =
      error && typeof error === "object" && "stderr" in error
        ? String((error as { stderr?: unknown }).stderr || "")
        : "";

    return durationSecondsFromFfmpegOutput(stderr);
  }
}

function durationSecondsFromFfmpegOutput(output: string) {
  const match = output.match(/Duration:\s*(\d+):(\d+):(\d+(?:\.\d+)?)/);

  if (!match) {
    return undefined;
  }

  return Number(match[1]) * 3600 + Number(match[2]) * 60 + Number(match[3]);
}

function partyMusicLavfiSource() {
  return [
    "aevalsrc=",
    "'",
    "0.08*sin(2*PI*220*t)*(gt(mod(t\\,0.5)\\,0.08))",
    "+0.06*sin(2*PI*277.18*t)*(gt(mod(t\\,0.5)\\,0.08))",
    "+0.05*sin(2*PI*329.63*t)*(gt(mod(t\\,0.5)\\,0.08))",
    "+0.04*sin(2*PI*440*t)*(gt(mod(t\\,0.25)\\,0.04))",
    "+0.05*sin(2*PI*880*t)*(lt(mod(t\\,1)\\,0.035))",
    "'",
    ":s=44100"
  ].join("");
}

export async function muxSongIntoVideo(
  videoUrl: string,
  songUrl: string,
  targetDurationSeconds = maxMuxedVideoDurationSeconds
) {
  return traceTool(
    "mux-song",
    () =>
      muxSongIntoVideoInner(videoUrl, songUrl, targetDurationSeconds),
    {
      metadata: { targetDurationSeconds }
    }
  );
}

async function muxSongIntoVideoInner(
  videoUrl: string,
  songUrl: string,
  targetDurationSeconds: number
) {
  const ffmpegBin = getFfmpegPath();
  if (!ffmpegBin) {
    throw new Error("ffmpeg binary is not available.");
  }

  const workspace = await mkdtemp(join(tmpdir(), "birthdaybot-song-"));

  try {
    const [video, song] = await Promise.all([
      mediaUrlToBuffer(videoUrl),
      mediaUrlToBuffer(songUrl)
    ]);
    const inputVideo = join(workspace, "input.mp4");
    const inputSong = join(workspace, "song.mp3");
    const outputVideo = join(workspace, "song-output.mp4");

    await writeFile(inputVideo, video.bytes);
    await writeFile(inputSong, song.bytes);

    const muxDuration = Math.min(
      Math.max(targetDurationSeconds || defaultVideoDurationSeconds, 1),
      maxMuxedVideoDurationSeconds
    );

    await execFileAsync(ffmpegBin, [
      "-y",
      "-i",
      inputVideo,
      "-i",
      inputSong,
      "-t",
      String(muxDuration),
      // Song is the only audio track. Loudnorm to social-mobile target so
      // it sits next to other media at parity volume; alimiter catches
      // any final transients.
      "-filter_complex",
      "[1:a:0]loudnorm=I=-16:LRA=11:TP=-1.5,alimiter=limit=0.97[aout]",
      "-map",
      "0:v:0",
      "-map",
      "[aout]",
      "-vf",
      "scale='if(gte(iw,ih),-2,720)':'if(gte(iw,ih),720,-2)'",
      "-c:v",
      "libx264",
      "-preset",
      "veryfast",
      "-b:v",
      `${finalVideoBitrateKbps}k`,
      "-maxrate",
      `${finalVideoBitrateKbps}k`,
      "-bufsize",
      `${finalVideoBitrateKbps * 2}k`,
      "-pix_fmt",
      "yuv420p",
      "-c:a",
      "aac",
      "-b:a",
      `${finalVideoAudioBitrateKbps}k`,
      "-shortest",
      "-metadata",
      "comment=AI-generated by BirthdayBot - song composed via ElevenLabs Music",
      "-movflags",
      "+faststart",
      outputVideo
    ]);

    const outputBytes = await readFile(outputVideo);
    return fal.storage.upload(
      new File([outputBytes], "birthday-song-video.mp4", { type: "video/mp4" })
    );
  } finally {
    await rm(workspace, { force: true, recursive: true });
  }
}

async function mediaUrlToBuffer(url: string) {
  if (url.startsWith("data:")) {
    const [header, data] = url.split(",");
    const mime = header.match(/data:(.*);base64/)?.[1] || "application/octet-stream";

    return {
      bytes: Buffer.from(data, "base64"),
      mime
    };
  }

  const response = await fetch(url);

  if (!response.ok) {
    throw new Error(await providerErrorMessage(response, "Media download failed."));
  }

  return {
    bytes: Buffer.from(await response.arrayBuffer()),
    mime: response.headers.get("content-type") || "application/octet-stream"
  };
}

async function providerErrorMessage(response: Response, fallback: string) {
  const body = await response.text().catch(() => "");
  const compactBody = body.replace(/\s+/g, " ").trim();

  if (!compactBody) {
    return fallback;
  }

  return `${fallback} ${compactBody.slice(0, 240)}`;
}

function getFfmpegPath() {
  try {
    const moduleName = ["ffmpeg", "-static"].join("");
    return require(moduleName) as string | undefined;
  } catch {
    return undefined;
  }
}
